### PR TITLE
WIP: State tracking

### PR DESCRIPTION
**Pull request by SamoZ256**
Changes in state (like render pipeline, depth stencil, etc) are tracked and these states are only bound if they changed. Render encoder state is created once at the start, as opposed to being recreated at every SetProgram. The problem with the previous approach was that SetEncoderState was called at the beginning of the render pass, but the program and vertex descriptor often change during the render pass, causing the encoder to use incorrect pipeline (it often used the default blit pipeline, which led to all sorts of weird problems). SetEncoderState is now called at every GetOrCreateRenderEncoder. Here is how SMO looks now:
smo_mario_rendered
Anyway, this PR probably needs some testing to ensure that it doesn't break anything.

### CODE REVIEW

**Comment by SamoZ256** [comment]
I have no idea why there are so many commits.

**Comment by SamoZ256** [comment]
I am also wondering when is the state reset, like depth stencil state, viewport, scissor, etc.

**Comment by IsaacMarovitz** [comment]
Screenshot 2024-05-18 at 09 00 49

This seems to cause regressions in Scott Pilgrim which suggests its maybe expecting state to be cleared somewhere where it is not.

**Comment by IsaacMarovitz** [comment]
> I have no idea why there are so many commits.

You likely need to rebase your branch again

**Comment by IsaacMarovitz** [comment]
> I am also wondering when (or if ever) the state is reset, like depth stencil state, viewport, scissor, etc.

GAL assumes OpenGL behaviour, ie all state persists and is never explicitly reset.

**Comment by SamoZ256** [comment]
Okay I made a commit that resets the state when program is changed (the way it was before), maybe it will work.

**Comment by SamoZ256** [comment]
> > I am also wondering when (or if ever) the state is reset, like depth stencil state, viewport, scissor, etc.
> 
> GAL assumes OpenGL behaviour, ie all state persists and is never explicitly reset.

Well that's strange, because in SMO, the depth stencil state is set once at the startup and is never changed, and using the same state all the time results in nothing being rendered.

**Comment by SamoZ256** [comment]
Also, how did Scott Pilgrim look without this PR?

**Comment by IsaacMarovitz** [comment]
> Also, how did Scott Pilgrim look without this PR?

SP barely rendered on the main branch, but it looked pretty good with your initial commit on the state tracking branch that got reworked into this PR.

**Comment by IsaacMarovitz** [comment]
> I had to reorganize things a bit, since the first commit on that branch was just a hack. But do you have a screenshot?

https://cdn.discordapp.com/attachments/410208622778384385/1240758387323703377/scott.mov

I general I recommend you join Ryujinx Discord as it makes communication about development a lot easier

**Pull request closed without merging**
